### ISSUE TITLE
testnet restart index from nBestHeight

### ISSUE THREAD

**Issue by dohaivu** [HTMLCOIN/HTMLCOIN#53]
Testnet is automatically restarted by error `Network is unreachable` and reindexed from `nBestHeight` (231148) which is far behind actually height (268124)

debug.log
```
2018-04-16 02:35:15 UpdateTip: new best=56944f6cbae151d3cc078542075590fbc95eb49b9b022be9a381d4348109a0f4 height=268174 version=0x20000000 log2_work=67.959349 tx=504486 date='2018-04-16 02:35:12' progress=1.000000 cache=21.0MiB(131964txo)
2018-04-16 02:35:15 ProcessNetBlock: ACCEPTED
2018-04-16 02:35:15 UpdateTip: new best=cc500b8e1477236689f9d697e48d6c1b2c0b8440b0fdebdb61b04b56942e2967 height=268175 version=0x20000000 log2_work=67.959358 tx=504488 date='2018-04-16 02:35:28' progress=1.000000 cache=21.0MiB(131967txo)
2018-04-16 02:35:15 ProcessNetBlock: ACCEPTED
2018-04-16 02:35:17 connect() to [2001:0:9d38:6abd:3c46:3262:2c34:4c7d]:14888 failed: Network is unreachable (101)
2018-04-16 02:35:17 connect() to [2405:204:e288:3399:d4c7:114b:1c78:ce14]:14888 failed: Network is unreachable (101)
2018-04-16 02:35:18 connect() to [2405:204:4019:de84:25b6:d7a2:34bb:4b41]:14888 failed: Network is unreachable (101)
2018-04-16 02:35:31 connect() to [2001:0:9d38:6abd:2caf:31b5:3cc3:4cde]:14888 failed: Network is unreachable (101)
2018-04-16 02:35:31 UpdateTip: new best=6ffe14b9abca15480b2725b2305da2614f094b72b732f97aece6e6f8d0a8a387 height=268176 version=0x20000000 log2_work=67.959367 tx=504490 date='2018-04-16 02:35:44' progress=1.000000 cache=21.0MiB(131972txo)
2018-04-16 02:35:32 ProcessNetBlock: ACCEPTED
2018-04-16 02:35:39 connect() to 211.203.179.130:14888 failed after select(): Connection refused (111)
2018-04-16 02:35:47 connect() to 203.252.229.93:14888 failed after select(): Connection refused (111)
2018-04-16 02:35:47 connect() to [2a02:8070:c69c:7300:3db9:10be:b58d:d4]:14888 failed: Network is unreachable (101)
2018-04-16 02:35:48 UpdateTip: new best=3ca37498b73ab8f10cd4015dc99e316268ffcfb3cd44bfa82a21bf9cc20c65a8 height=268177 version=0x20000000 log2_work=67.959376 tx=504492 date='2018-04-16 02:36:00' progress=1.000000 cache=21.0MiB(131975txo)
2018-04-16 02:35:48 ProcessNetBlock: ACCEPTED
2018-04-16 02:35:56 





2018-04-16 02:35:56 HTMLCOIN version v2.0.2.1-beta
2018-04-16 02:35:56 InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
2018-04-16 02:35:56 Assuming ancestors of block 00000000000128796ee387cf110ccb9d2f36cffaf7f73079c995377c65ac0dcc have valid signatures.
2018-04-16 02:35:57 Default data directory /home/node/.htmlcoin
2018-04-16 02:35:57 Using data directory /home/node/mynode-data/testnet3
2018-04-16 02:35:57 Using config file /home/node/mynode/htmlcoin.conf
2018-04-16 02:35:57 Using at most 3 automatic connections (1048576 file descriptors available)
2018-04-16 02:35:57 Using 32 MiB out of 32 requested for signature cache, able to store 1048576 elements
2018-04-16 02:35:57 Using 2 threads for script verification
2018-04-16 02:35:57 scheduler thread start
2018-04-16 02:35:57 Binding RPC on address 0.0.0.0 port 14889 failed.
2018-04-16 02:35:57 HTTP: creating work queue of depth 16
2018-04-16 02:35:57 Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpcuser for rpcauth auth generation.
2018-04-16 02:35:57 HTTP: starting 4 worker threads
2018-04-16 02:35:57 Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2018-04-16 02:35:57 Using wallet wallet.dat
2018-04-16 02:35:57 init message: Verifying wallet...
2018-04-16 02:35:57 CDBEnv::Open: LogDir=/home/node/mynode-data/testnet3/database ErrorFile=/home/node/mynode-data/testnet3/db.log
2018-04-16 02:35:57 Bound to [::]:14888
2018-04-16 02:35:57 Bound to 0.0.0.0:14888
2018-04-16 02:35:57 Cache configuration:
2018-04-16 02:35:57 * Using 15.0MiB for block index database
2018-04-16 02:35:57 * Using 2.5MiB for chain state database
2018-04-16 02:35:57 * Using 2.5MiB for in-memory UTXO set (plus up to 47.7MiB of unused mempool space)
2018-04-16 02:35:57 init message: Loading block index...
2018-04-16 02:35:57 Opening LevelDB in /home/node/mynode-data/testnet3/blocks/index
2018-04-16 02:35:58 Opened LevelDB successfully
2018-04-16 02:35:58 Using obfuscation key for /home/node/mynode-data/testnet3/blocks/index: 0000000000000000
2018-04-16 02:35:58 Opening LevelDB in /home/node/mynode-data/testnet3/chainstate
2018-04-16 02:35:58 Opened LevelDB successfully
2018-04-16 02:35:58 Using obfuscation key for /home/node/mynode-data/testnet3/chainstate: eb8b92ca3d78e6ef
2018-04-16 02:36:08 LoadBlockIndexDB: last block file = 1
2018-04-16 02:36:08 LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=42725, size=26340624, heights=0...267915, time=2017-09-24...2018-04-16)
2018-04-16 02:36:08 LoadBlockIndexDB(): synchronized checkpoint 000013694772f8aeb88efeb2829fe5d71fbca3e23d5043baa770726f204f528c
2018-04-16 02:36:08 Checking all blk files are present...
2018-04-16 02:36:08 LoadBlockIndexDB: transaction index enabled
2018-04-16 02:36:08 LoadBlockIndexDB(): address index enabled
2018-04-16 02:36:08 LoadBlockIndexDB: log events index enabled
2018-04-16 02:36:08 LoadBlockIndexDB: hashBestChain=88fc88505602a3be7e696cd3bf66b665c20363e2855c361ad7b989f360c35953 height=231148 date=2018-04-09 04:40:32 progress=1.000000
2018-04-16 02:36:08 Opened LevelDB successfully
2018-04-16 02:36:08 init message: Rewinding blocks...
2018-04-16 02:36:10 init message: Verifying blocks...
2018-04-16 02:36:10 Verifying last 6 blocks at level 3
2018-04-16 02:36:10 [0%]...[16%]...[33%]...[50%]...[66%]...[83%]...[99%]...[DONE].
2018-04-16 02:36:11 No coin database inconsistencies in last 7 blocks (13 transactions)
2018-04-16 02:36:11  block index           14254ms
2018-04-16 02:36:11 init message: Loading wallet...
2018-04-16 02:36:12 nFileVersion = 2000201
2018-04-16 02:36:12 Keys: 102 plaintext, 0 encrypted, 102 w/ metadata, 102 total
2018-04-16 02:36:12  wallet                   21ms
2018-04-16 02:36:12 setKeyPool.size() = 100
2018-04-16 02:36:12 mapWallet.size() = 0
2018-04-16 02:36:12 mapAddressBook.size() = 1
2018-04-16 02:36:12 mapBlockIndex.size() = 268124
2018-04-16 02:36:12 nBestHeight = 231148
2018-04-16 02:36:12 init message: Loading addresses...
2018-04-16 02:36:12 torcontrol thread start
2018-04-16 02:36:12 Loaded 322 addresses from peers.dat  9ms
2018-04-16 02:36:12 init message: Loading banlist...
2018-04-16 02:36:12 init message: Starting network threads...
2018-04-16 02:36:12 init message: Done loading
2018-04-16 02:36:12 msghand thread start
2018-04-16 02:36:12 opencon thread start
2018-04-16 02:36:12 addcon thread start
2018-04-16 02:36:12 dnsseed thread start
2018-04-16 02:36:12 net thread start
2018-04-16 02:36:12 UpdateTip: new best=04b98b062ee231ce00a7008047c1c4822f573245414c87592df3ff295780f4e7 height=231149 version=0x20000000 log2_work=67.590898 tx=432020 date='2018-04-09 04:40:48' progress=1.000000 cache=0.0MiB(5txo)
2018-04-16 02:36:12 UpdateTip: new best=9fff717a7e7e7d1404788ccd2701c32a781adf54e076d20f6b7cdd4cf5e50a97 height=231150 version=0x20000000 log2_work=67.59091 tx=432022 date='2018-04-09 04:41:04' progress=1.000000 cache=0.0MiB(10txo)
2018-04-16 02:36:12 UpdateTip: new best=9f4af016267bc41a40e62a3881213387ad0439f024512d20e6df2a36b6ce94f4 height=231151 version=0x20000000 log2_work=67.590921 tx=432024 date='2018-04-09 04:41:20' progress=1.000000 cache=0.0MiB(15txo)
2018-04-16 02:36:12 UpdateTip: new best=876ea4053a6031f2a25dc1fec1ea4181b36fa7ce6ac73ee5a9c9946a17cbe957 height=231152 version=0x20000000 log2_work=67.590933 tx=432026 date='2018-04-09 04:41:36' progress=1.000000 cache=0.0MiB(20txo)
```

**Comment by sunk818** [comment]
If you sync successfully, the last block height should be committed. If your wallet errors out or otherwise exists abnormally, you may need to resync the blockchain from the last commited point. This is normal.

**Comment by dohaivu** [comment]
It seems that testnet is restarted because an error on htmlcoincore-node

```
[2018-04-17T11:15:17.199Z] info: HTMLCOIN Height: 275018 Percentage: 100.00
[2018-04-17T11:15:18.379Z] error: [ERC20WATCHER] Update Error { RPCError: HTMLCOIN JSON-RPC: Request Error: socket hang up
    at HTMLCOIN._wrapRPCError (/home/node/mynode/node_modules/htmlcoincore-node/lib/services/htmlcoind.js:551:13)
    at /home/node/mynode/node_modules/htmlcoincore-node/lib/services/htmlcoind.js:1771:28
    at ClientRequest.<anonymous> (/home/node/mynode/node_modules/htmlcoind-rpc/lib/index.js:116:7)
    at ClientRequest.emit (events.js:159:13)
    at Socket.socketOnEnd (_http_client.js:423:9)
    at Socket.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19) code: undefined }
[2018-04-17T11:15:18.381Z] error: [STATISTICS] Update Error { RPCError: HTMLCOIN JSON-RPC: Request Error: socket hang up
    at HTMLCOIN._wrapRPCError (/home/node/mynode/node_modules/htmlcoincore-node/lib/services/htmlcoind.js:551:13)
    at /home/node/mynode/node_modules/htmlcoincore-node/lib/services/htmlcoind.js:2124:28
    at ClientRequest.<anonymous> (/home/node/mynode/node_modules/htmlcoind-rpc/lib/index.js:116:7)
    at ClientRequest.emit (events.js:159:13)
    at Socket.socketOnEnd (_http_client.js:423:9)
    at Socket.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19) code: undefined }
[2018-04-17T11:15:18.384Z] error: [AddressBalanceService] Update Error { RPCError: HTMLCOIN JSON-RPC: Request Error: socket hang up
    at HTMLCOIN._wrapRPCError (/home/node/mynode/node_modules/htmlcoincore-node/lib/services/htmlcoind.js:551:13)
    at /home/node/mynode/node_modules/htmlcoincore-node/lib/services/htmlcoind.js:1213:30
    at ClientRequest.<anonymous> (/home/node/mynode/node_modules/htmlcoind-rpc/lib/index.js:116:7)
    at ClientRequest.emit (events.js:159:13)
    at Socket.socketOnEnd (_http_client.js:423:9)
    at Socket.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19) code: undefined }
[2018-04-17T11:15:18.539Z] warn: HTMLCOIN process unexpectedly exited with code: null
[2018-04-17T11:15:18.540Z] warn: Restarting htmlcoin child process in 5000ms
[2018-04-17T11:15:18.680Z] warn: ZMQ disconnect: tcp://127.0.0.1:28332
[2018-04-17T11:15:18.681Z] warn: ZMQ connection delay: tcp://127.0.0.1:28332
```

**Comment by Bushstar** [comment]
In 2.0.3 we have several upstream changes and the UTXO cache fix in seven days time on testnet, at the same time as the UTXO cache fix the blocktime for testnet will increase from 10 seconds to 60 seconds. Blocks are coming in far too fast on testnet and the daemon and services seem to struggle with the load.
